# Generated by Django 5.1.2 on 2024-12-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Course ',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='dars nomi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='dars matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post/photos/', verbose_name='Rasmi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published', models.BooleanField(default=True, help_text="Belgilangan bo'lsa, saytga chiqaradi!", verbose_name='Saytga chiqarish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.course', verbose_name='Kategororiyasi')),
            ],
            options={
                'verbose_name': 'Lesson ',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-created'],
            },
        ),
    ]
